[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tucan"
authors = [{ name = "Jan C. Brammer", email = "jan.brammer@pm.me" }]
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
]
dynamic = ["version"]

dependencies = [
    "networkx >=3.4",
    "scipy >=1.15.3",
    "antlr4-python3-runtime == 4.13.2",
]

[project.optional-dependencies]
drawing = [
    "plotly",         # interactive 3D drawings
    "notebook",
    "ipywidgets",
    "matplotlib",
    "tabulate",
    "types-tabulate",
]
dev = ["pytest", "pytest-timeout", "syrupy"]


[tool.pytest.ini_options]
minversion = "9.0"
addopts = """
    -v
    --durations=5"""
testpaths = ["tests"]

[tool.black] # https://lyz-code.github.io/blue-book/devops/black/
extend-exclude = 'tucan/parser/tucan.*\.py'

[tool.mypy]
ignore_missing_imports = true
exclude = ["parser/"]

[[tool.mypy.overrides]]
module = "tucan.parser.*"
follow_imports = "skip"
